---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flux
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io.port: '3031'
      labels:
        name: flux
    spec:
      serviceAccount: flux
      volumes:
        - name: git-key
          secret:
            secretName: flux-git-deploy
            defaultMode: 0400
        - name: git-keygen
          emptyDir:
            medium: Memory
      containers:
        - name: flux
          image: weaveworks/flux:1.8.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          ports:
            - containerPort: 3030
          volumeMounts:
            - name: git-key
              mountPath: /etc/fluxd/ssh
              readOnly: true
            - name: git-keygen
              mountPath: /var/fluxd/keygen
          args:
            - --memcached-hostname=memcached.flux.svc.cluster.local
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --git-url=git@github.com:Naresh240/spring-boot-hello.git
            - --git-branch=master
